### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by ghost** [beisci/SleepInfo#1]
Dear Dr. Bei Bei
I am a psychiatrist living in Tokyo, Japan.
I was impressed by your article about sleep in this turmoil. So I translated the piece into Japanese. Would you mind if I share this?

[sleep_in_isolation_jp.md.txt](https://github.com/beisci/SleepInfo/files/4414018/sleep_in_isolation_jp.md.txt)

**Comment by beib** [comment]
Hi @tan93nt 
Thank you so much for this! Could you please let me know your name and affiliation? I would like to add this to the acknowledgement. If you could also add this in the Japanese version that would be great! 
Once I pushed these to the master branch, please feel free to send pull request if you need to make changes. 
Best wishes,
Bei

**Comment by beib** [comment]
@tan93nt Of course you are welcome to share it. Would you mind if we add a link to your Japanese version in the English version, and acknowledge your translation?

**Comment by ghost** [comment]
@beib Thank you for your reply. 
My name is Y Tomioka. I currently have no specific affiliation.  
No, I would not mind adding a link at all.

Best regards,

**Comment by beib** [comment]
Thank you @tan93nt . I have updated everything to include the Japanese version. Take care and keep safe!

**Comment by ghost** [comment]
Thank you for your quick response!
Take care, too.

**Comment by beib** [comment]
@tan93nt, we have a new guide on how to support people to make changes to their sleep timing out of pandemic, see here: https://github.com/beisci/SleepInfo/blob/master/sleep_transition.md
If you would like to translate it to Japanese, please let me know, and I'll link to your Japanese version like we did before with the first guide. Thanks! :)
